### ISSUE TITLE
Tracks play for only a few seconds before pausing

### ISSUE THREAD

**Issue by rgov** [rectalogic/mopidy-pandora#61]
I'm troubleshooting an issue where a Pandora track will start playing immediately, but only for about 2 seconds before it playback pauses. Usually it will continue after a long wait. My hunch is that it's a stream buffering issue.

Here's a [Mopidy Discuss post](https://discuss.mopidy.com/t/only-a-few-seconds-of-audio-before-it-stops/1517) about the issue with more information.

**Comment by jcass77** [comment]
This sounds like a more general Mopidy buffering issue and probably not related to Mopidy-Pandora.

Other things that you could try to troubleshoot:

- [run pydora directly](https://github.com/rectalogic/mopidy-pandora/blob/develop/docs/troubleshooting.rst#5-run-pydora-directly). This should point out whether the issue is related to Mopidy / gstreamer, or whether it is a network issue.

- if you are connecting to a wifi network, try using a cable connection instead. There have been reports of Pandora not working on some (especially public / dormitory) wifi networks.

- try one of the other streaming backend extensions [Mopidy-GMusic](https://github.com/mopidy/mopidy-gmusic) is probably the most similar to Mopidy-Pandora.

**Comment by jcass77** [comment]
Closing after long period of inactivity - please update if this is still an issue.
