### ISSUE TITLE
Pandora track skip limit exceeded - how to know when a track is playable?

### ISSUE THREAD

**Issue by SharKCS11** [rectalogic/mopidy-pandora#67]
Hi all, I'm creating an application that switches pandora stations (on a free account) somewhat frequently, but _doesn't try to manually skip tracks_. The sequence is: clear tracklist, add pandora station, play. Mopidy automatically loads tracks from the station and plays them. For the most part, it's working very well.
I often get this: "track is not playable: pandora:ad:..." Usually this isn't a problem and it can go to the next track.

However, occasionally I get warnings like this in a row:

> WARNING  Track is not playable: pandora:ad:4092143028425283980:4092143028425283980-pod%3A1/2/8
> WARNING  Maximum track skip limit (5) exceeded.
> WARNING  Track is not playable: pandora:ad:4092143028425283980:4092143028425283980-pod%3A2/2/

When this happens, the next track doesn't play, and the station is just silent. 

I looked at issue #43 so I want to ask what determines when a pandora track is playble? Are ads always not playable? Because sometimes the ads _will_ successfully play. Other times only the tracks will play, and rarely I'll get the issue I just described where nothing plays. Restarting mopidy fixes the problem, as noted in #43, but I'll try to avoid it if there's a better way.
Thanks in advance!

**Comment by jcass77** [comment]
As far as I can recall, Pandora also serves non-audio visual ads that appear as image popups in the official applications. I suspect being served those types of ads might be the cause of ads sometimes being reported as not playable, but as you mentioned mopidy-pandora usually just skips to the next track so it isn't really a problem.

The ``Maximum track skip limit (5) exceeded`` message is due to a built-in failsafe that prevents mopidy-pandora from skipping more than 5 tracks in a row. If more than 5 skips are required to get to the next playable track it is usually an error condition, and this prevents mopidy-pandora form flooding the Pandora server with track requests that could result in your account being throttled.

I *think* the problems that you are experiencing is due to switching between stations a lot. Pandora registers each switch to a new station as a track 'skip' as well to prevent people from avoiding ads by just switching to another station. So this could be increasing the skip count for your account. The Pandora server will eventually become very aggressive and only serve up ads if it thinks that you are trying to skip all of them.

I haven't used a free account in a number of years so not sure how viable it is to use them reliably with mopidy-pandora anymore, as Pandora's ad-serving policies do seem to change from time to time.

**Comment by SharKCS11** [comment]
Alright, makes sense. I'll most probably try a paid account by the end of this project.
